# Generated by Django 6.0 on 2026-01-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_reservation_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=20)),
            ],
        ),
    ]
