# Generated by Django 6.0.1 on 2026-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
